### ISSUE TITLE
Pipeline does not seem to work with non-stranded data

### ISSUE THREAD

**Issue by Romicak** [shalgilab/DoGFinder#4]
Hi,

I tried running this pipeline for RNA-seq data that is not strand specific. The pipeline seems to be failing at step 2- the pre processing BAM fiels step. It seems to generate new BAM files with "PE" appended at the end. However, those BAM files are empty when I checked. Consequently, the next step which is downsampling fails, I get these errors:
`-----------------------------------------------------Pre_Process-------------------------------------------------------------------------
Ref. file: loci_annotation_genecode_mm10.bed
Cores available: 72 Cores usage: 2
Processing and counting bam files...
Reading reference gene model loci_annotation_genecode_mm10.bed ... Done
Loading SAM/BAM file ...  Total 200000 usable reads were sampled
Reading reference gene model loci_annotation_genecode_mm10.bed ... Done
Loading SAM/BAM file ...  Total 200000 usable reads were sampled
/research/Human/RNASeq/DrUrrutia/iKras_knockout_18S_062518/Maprseq3/maprseq3/output/bams/scramb+doxy_rep1.Aligned.sortedByCoord.out.sorted_PE.bam : Paired-Ended, Not stranded, with 0.0 mapped Mreads
/research/Human/RNASeq/DrUrrutia/iKras_knockout_18S_062518/Maprseq3/maprseq3/output/bams/scramb-doxy_rep1.Aligned.sortedByCoord.out.sorted_PE.bam : Paired-Ended, Not stranded, with 0.0 mapped Mreads
Bam file: /research/Human/RNASeq/DrUrrutia/iKras_knockout_18S_062518/Maprseq3/maprseq3/output/bams/scramb+doxy_rep1.Aligned.sortedByCoord.out.sorted_PE.bam has smallest number of mapped reads: 0.0 Mreads
Downsampling...
Process Process-4:
Traceback (most recent call last):
  File "/apps/python/2.7.15/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
Process Process-3:
Traceback (most recent call last):
  File "/apps/python/2.7.15/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/apps/python/2.7.15/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/apps/python/2.7.15/bin/Pre_Process", line 21, in do_job
    self.run()
  File "/apps/python/2.7.15/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/apps/python/2.7.15/bin/Pre_Process", line 21, in do_job
    reads_count_0,bam_names,PE,strand=func(*args)
  File "/apps/python/2.7.15/bin/Pre_Process", line 37, in myfunc2
    DoGs_functions.Downsample(k,bam_names_new,output_path,reads_min_count)
  File "/apps/python/2.7.15/lib/python2.7/site-packages/DoGs_functions/__init__.py", line 278, in Downsample
    reads_count_0,bam_names,PE,strand=func(*args)
  File "/apps/python/2.7.15/bin/Pre_Process", line 37, in myfunc2
    DoGs_functions.Downsample(k,bam_names_new,output_path,reads_min_count)
  File "/apps/python/2.7.15/lib/python2.7/site-packages/DoGs_functions/__init__.py", line 278, in Downsample
    s=reads_min_count/reads_count
ZeroDivisionError: float division by zero
    s=reads_min_count/reads_count
ZeroDivisionError: float division by zero
^CTraceback (most recent call last):
  File "/apps/python/2.7.15/bin/Pre_Process", line 203, in <module>
    main()
  File "/apps/python/2.7.15/bin/Pre_Process", line 191, in main
    tmp=tasks_out_count.qsize()
`
I don't have these errors when the data is stranded. I was looked inside the "__init__.py" file and found that if that data is stranded, based on strand == 'second' or strand == 'first' it performs certain functions, however I did not find any execution functions for when the strand =='none'. I am not sure if this could be contributing to the error.

**Comment by sagarutturkar** [comment]
I am facing the same problem. My data is stranded, it works for several samples that were sequenced similarly but fails for two samples. Let me know if there is any workaround.

**Comment by sagarutturkar** [comment]
After the response from authors, I updated the tool to newest version (Nov 2020 ) and it worked well for all the steps.
