### ISSUE TITLE
Error in Get_DoGs_rpkm (bedtools coverage)

### ISSUE THREAD

**Issue by dsobral** [shalgilab/DoGFinder#5]
Hello,

When running Get_DoGs_rpkm I get an error with bedtools (see below).
The solution would be "simple" in pinciple.
It should be to add the -g parameter to the bedtools command, and the user would have to provide a genome file.

I'm not sure if you have plans to include that, or suggest something else?

`Traceback (most recent call last):
  File "/opt/conda/bin/Get_DoGs_rpkm", line 106, in <module>
    annota_cov=annot_sort.coverage(reads,sorted=True,s=S,split=True)
  File "/opt/conda/lib/python2.7/site-packages/pybedtools/bedtool.py", line 840, in decorated
    result = method(self, *args, **kwargs)
  File "/opt/conda/lib/python2.7/site-packages/pybedtools/bedtool.py", line 345, in wrapped
    decode_output=decode_output,
  File "/opt/conda/lib/python2.7/site-packages/pybedtools/helpers.py", line 434, in call_bedtools
    raise BEDToolsError(subprocess.list2cmdline(cmds), stderr)
pybedtools.helpers.BEDToolsError:
Command was:

        bedtools coverage -split -sorted -s -b /mnt/share/file.sorted.bam -a /tmp/pybedtools.eBdOBs.tmp

Error message was:
ERROR: Database file /mnt/share/file.sorted.bam contains chromosome chrM, but the query file does not.
       Please re-reun with the -g option for a genome file.
       See documentation for details.`

Thanks

**Comment by dsobral** [comment]
I noticed now that there's already a pull request to solve this issue.
