### ISSUE TITLE
Error at Get_DoGs step

### ISSUE THREAD

**Issue by sagarutturkar** [shalgilab/DoGFinder#6]
I am facing following two issues:

1. **Pre_Process** step does not recognize paired-end BAM files generated with STAR aligner, the log file says **Not Paired-End, Not stranded**.
2.  When I proceed with generated BAM files (i.e. *_DS.bam), In step **Get_DoGs**, I get python error as:

```
Traceback (most recent call last):
  File "/group/bioinfo/apps/apps/DoGFinder-Jun-29-2020/bin/Get_DoGs", line 250, in <module>
    df_max_dog_length['size_opp']=df_max_dog_length_opp;
  File "/group/bioinfo/apps/apps/Python-2.7.12/lib/python2.7/site-packages/pandas/core/frame.py", line 3119, in __setitem__
    self._set_item(key, value)
  File "/group/bioinfo/apps/apps/Python-2.7.12/lib/python2.7/site-packages/pandas/core/frame.py", line 3193, in _set_item
    self._ensure_valid_index(value)
  File "/group/bioinfo/apps/apps/Python-2.7.12/lib/python2.7/site-packages/pandas/core/frame.py", line 3175, in _ensure_valid_index
    raise ValueError('Cannot set a frame with no defined index '
ValueError: Cannot set a frame with no defined index and a value that cannot be converted to a Series

``` 

Hopefully someone can help with resolving this error.

**Comment by sagarutturkar** [comment]
As per the response from author - DogFinder needs specific version of BEDTools (v2.26.0) and then it worked fine. I still get an error at "Get_DoGs_rpkm" step - but at least I have the DoGs called which could be processed in different manner.

If you are still getting error - note that BEDTools has integrated samtools (which could be older version) and you may need to reload latest version of samtools after loading the BEDTools.

Hopefully, this will help someone.
