### ISSUE TITLE
Get_DoGs issues

### ISSUE THREAD

**Issue by iris-summer** [shalgilab/DoGFinder#7]
Hello,

I'm using human genome hg38 to run Get_Dogs. My bam file is strand-specific and merge the R1 and R2 by pear before Hisat2 alignment. I meet the problem when I running the Get_DoGs. "-s" was used.

Path of reads to run pipe on: /blue/mingyi.xie/tianqi.li/ribo_INTS11_KD/TL_ribodepletion_4sU_C_mutation/ribo_depletion/ribo_WT_siInt11_plus_plus/filter/WT-siInt11-plus-plus.assembled_slamdunk_mapped_filtered.sorted_DS.bam 
Annotation file: /blue/mingyi.xie/tianqi.li/ribo_INTS11_KD/annotationdir/loci_annotation.bed 
output will be at: /blue/mingyi.xie/tianqi.li/ribo_INTS11_KD/TL_ribodepletion_4sU_C_mutation/ribo_depletion/Dogfinder/

Mode is -F: Coverage on total DoG length
Paremeters: First coverage on: 4000nt, First coverage cutoff: 0.6, Running window size: 200nt, DoGs end cutoff: 0.6
Not Strand specific 

Found index file: /blue/mingyi.xie/tianqi.li/ribo_INTS11_KD/TL_ribodepletion_4sU_C_mutation/ribo_depletion/ribo_WT_siInt11_plus_plus/filter/WT-siInt11-plus-plus.assembled_slamdunk_mapped_filtered.sorted_DS.bam.bai
Searching for non genic reads file in /blue/mingyi.xie/tianqi.li/ribo_INTS11_KD/TL_ribodepletion_4sU_C_mutation/ribo_depletion/ribo_WT_siInt11_plus_plus/filter 
Found non_genic bed file in dir: /blue/mingyi.xie/tianqi.li/ribo_INTS11_KD/TL_ribodepletion_4sU_C_mutation/ribo_depletion/ribo_WT_siInt11_plus_plus/filter/WT-siInt11-plus-plus.assembled_slamdunk_mapped_filtered.sorted_DS_no_gene_sorted.bed

***** WARNING: File /tmp/pybedtools.o7_SLl.tmp has inconsistent naming convention for record:
chr1	0	1	chr1	0	-

***** WARNING: File /tmp/pybedtools.o7_SLl.tmp has inconsistent naming convention for record:
chr1	0	1	chr1	0	-

***** WARNING: File /tmp/pybedtools.o7_SLl.tmp has inconsistent naming convention for record:
chr1	0	1	chr1	0	-

***** WARNING: File /tmp/pybedtools.o7_SLl.tmp has inconsistent naming convention for record:
chr1	0	1	chr1	0	-

First coverage...
***** WARNING: File /blue/mingyi.xie/tianqi.li/ribo_INTS11_KD/TL_ribodepletion_4sU_C_mutation/ribo_depletion/ribo_WT_siInt11_plus_plus/filter/WT-siInt11-plus-plus.assembled_slamdunk_mapped_filtered.sorted_DS_no_gene_sorted.bed has inconsistent naming convention for record:
chr1	629434	629519	A00916:54:HFHL2DSXY:4:1544:26268:6339	60	+

ERROR: Sort order was unspecified, and file /blue/mingyi.xie/tianqi.li/ribo_INTS11_KD/TL_ribodepletion_4sU_C_mutation/ribo_depletion/ribo_WT_siInt11_plus_plus/filter/WT-siInt11-plus-plus.assembled_slamdunk_mapped_filtered.sorted_DS_no_gene_sorted.bed is not sorted lexicographically.
       Please rerun with the -g option for a genome file.
       See documentation for details.
Number of DoGs found :  102
Elongating DoGs to find DoGs end...

Traceback (most recent call last):
  File "/apps/dogfinder/20201103/bin/Get_DoGs", line 339, in <module>
    annotation_combine_windows_cov=annotation_combine_windows.coverage(reads_for_pipe,sorted=True,s=s_strand,S=S_strand)
  File "/apps/dogfinder/20201103/lib/python2.7/site-packages/pybedtools/bedtool.py", line 917, in decorated
    result = method(self, *args, **kwargs)
  File "/apps/dogfinder/20201103/lib/python2.7/site-packages/pybedtools/bedtool.py", line 401, in wrapped
    decode_output=decode_output,
  File "/apps/dogfinder/20201103/lib/python2.7/site-packages/pybedtools/helpers.py", line 455, in call_bedtools
    raise BEDToolsError(subprocess.list2cmdline(cmds), stderr)
pybedtools.helpers.BEDToolsError: 
Command was:

	bedtools coverage -sorted -b /blue/mingyi.xie/tianqi.li/ribo_INTS11_KD/TL_ribodepletion_4sU_C_mutation/ribo_depletion/ribo_WT_siInt11_plus_plus/filter/WT-siInt11-plus-plus.assembled_slamdunk_mapped_filtered.sorted_DS_no_gene_sorted.bed -a /tmp/pybedtools.uO1Euz.tmp

Error message was:
ERROR: Sort order was unspecified, and file /blue/mingyi.xie/tianqi.li/ribo_INTS11_KD/TL_ribodepletion_4sU_C_mutation/ribo_depletion/ribo_WT_siInt11_plus_plus/filter/WT-siInt11-plus-plus.assembled_slamdunk_mapped_filtered.sorted_DS_no_gene_sorted.bed is not sorted lexicographically.
       Please rerun with the -g option for a genome file.
       See documentation for details.

Best,
Iris

**Comment by shalgilab** [comment]
Hi Iris,
Since you combined the R1 and R2 reads, currently your data is not strand specific as you can see in the script output in line 14 of your message. You can try to run again without the -s option. don't forget to delete the non_genic bed file (/blue/mingyi.xie/tianqi.li/ribo_INTS11_KD/TL_ribodepletion_4sU_C_mutation/ribo_depletion/ribo_WT_siInt11_plus_plus/filter/WT-siInt11-plus-plus.assembled_slamdunk_mapped_filtered.sorted_DS_no_gene_sorted.bed ) so it will be created again with the correct parameter.

But either way, I recommend to map the data as paired-end before using the tool. 
Good luck,
Shani
