### ISSUE TITLE
Get_loci_annotation error (pybedtools)

### ISSUE THREAD

**Issue by niekwit** [shalgilab/DoGFinder#9]
I am trying to run `Get_loci_annotation` as follows:
```
Get_loci_annotation -out . -gtf home/user/Documents/gtf/hg38/Homo_sapiens.GRCh38.106.chr_patch_hapl_scaff.gtf
```
But I get the following error:
```
Traceback (most recent call last):
  File "/usr/local/bin/Get_loci_annotation", line 2, in <module>
    import pybedtools
  File "/home/niek/.local/lib/python2.7/site-packages/pybedtools/__init__.py", line 16, in <module>
    from . import contrib
  File "/home/niek/.local/lib/python2.7/site-packages/pybedtools/contrib/__init__.py", line 4, in <module>
    from . import long_range_interaction
  File "/home/niek/.local/lib/python2.7/site-packages/pybedtools/contrib/long_range_interaction.py", line 357
    print("%d (%.1f%%)\r" % (c, c / float(n) * 100), end="")
                                                        ^
SyntaxError: invalid syntax
```
I have installed the required Python2 packages without any errors.

**Comment by niekwit** [comment]
I have had a look at the pybedtools web site and found the following:
```
Changes in v0.9
2022-01-23
Code cleanup:

**Removed some remnants of Python 2.7 support** (thanks @DavidCain)
```

Would it be possible to make DoGFinder compatible with Python3? RSeqC should be compatible with Python3 since V3.0.0 (http://rseqc.sourceforge.net). Thank you.
